version: '3.5'

services:

    fr_server:
        build: 
            context: ./backend/
            dockerfile: backend.dockerfile
        image: fr_server:v1
        container_name: fr_server
        networks:
            - fr_server_network
        ports:
            - 8000:8000
        # volumes:
        #     - type: volume
        #       source: analytics_data
        #       target: /aijs_app/data/
        #       volume:
        #         nocopy: true
            # - type: bind
            #   source: ./AppData/filesystem/NIMAIQA
            #   target: /aijs_app/data/

        env_file:
            - fr_server.env
        restart: unless-stopped
        
networks:
    fr_server_network:
        external: True
        name: fr_network

        
