version: '3.5'

services:

    fr_minio_mc:
        image: minio/mc
        container_name: fr_minio_mc
        env_file:
            - .env
        networks:
            - fr_db_network
        command: mc config host add myminio fr_minio minio minio123
    

networks:
    fr_db_network:
        driver: bridge
        external: true
        name: fr_network
