
pipeline:
  - multi_uri_src: nvmultiurisrcbin
  - branch_out: # keywork to split into branches
    - branch_infer: # branch name
      # - concurrency: 3 # number of concurrent branches of branch_infer
      - pgie: nvinferserver
    - branch_infer_1:
      - pgie_1: nvinferserver
    - branch_infer_2:
      - pgie_2: nvinferserver

  # working till here
  - branch_in: # keyword to join branches
    - branches_to_link: [pgie, pgie_1, pgie_2] # list of branches to join
    - meta_mux: nvdsmetamux
  
  - branch_out:
    - branch_kafka:
        - kafka_tail_components 
    - branch_osd:
      - osd_pipeline_components
      - branch_out:
        - branch_filesink:
          - file_sink_tail_components
        - branch_rtsp:
          - rtsp_sink_tail_components
      
  - branch_in: # keyword to join branches
    - branches_to_link: [branch_rtsp, branch_kafka] # list of branches to join
    - meta_mux: nvmetamux
  - fake_sink_tail_components
  