version: '3'

services:
  edgeai_core_api:
    build:
      context: ../
      dockerfile: docker/core_api.Dockerfile
    image: egdeai_core_api:v1
    container_name: egdeai_core_api
    ports:
      - "8090:8090"
    networks:
      - edgeai_network

networks:
  edgeai_network:
    external: True
    name: edgeai_network