version: '3'

services:

    edgeai_minio:
        image: quay.io/minio/minio
        container_name: edgeai_minio
        restart: unless-stopped
        volumes:
            - data1-1:/data
            # - data1-2:/data2
        ports:
            - 9000:9000
            - 9090:9090
        env_file:
            - .env
        command: server /data --console-address ":9090"

        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3


    edgeai_redis:
        image: redis:latest
        container_name: edgeai_redis
        restart: unless-stopped
        hostname: edgeai_redis
        ports:
            - 6379:6379
        depends_on:
            - edgeai_minio
        

    edgeai_pgdb:
        image: postgres:latest
        container_name: edgeai_postgresdb
        restart: unless-stopped
        ports:
            - 5432:5432
        env_file:
            - .env
        depends_on:
            - edgeai_redis

    
    edgeai_mongodb:
        image: mongo:latest
        container_name: edgeai_mongodb
        restart: unless-stopped
        depends_on:
            - edgeai_pgdb
        ports:
            - 27017:27017
        env_file:
            - .env

    
    edgeai_pgadmin:
        image: dpage/pgadmin4:latest
        container_name: edgeai_pgadmin
        restart: unless-stopped
        env_file:
            - .env
        depends_on:
            - edgeai_pgdb
        ports:
            - 5050:80
     
# volumes:
#     redis_data:
#         name: edgeai_redis_data
#     pgdb_data:
#         name: edgeai_pgdb_data
#     mdb_data:
#         name: edgeai_mdb_data
#     pgad_data:
#         name: edgeai_pgad_data
            
volumes:
    data1-1:
    data1-2: