name: EAI CORE API

on:
  push:
    branches: [ "dev" ]
    paths: 
      - "eai_core_api/**"
  
  pull_request:
    branches: [ "dev" ]
    paths: 
      - "eai_core_api/**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: eai_core_api

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Compose
      uses: isbang/compose-action@v1.4.1
      with:
        compose-file: |
          ./eai_core_api/docker/compose.edgeai_db.yml

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f ./requirements.txt ]; then pip install -r ./requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Run server and test with pytest
      run: |

        python3 main.py &
        sleep 5
        ls -l
        pytest -v --trace


  docker-publish:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: eai_core_api

    steps:
    - uses: actions/checkout@v3
  
    - name: Build the Docker image
      run: docker build . --file docker/core_api.Dockerfile --tag ghcr.io/${{ github.repository }}/my-image-name:$(date +%s)
      
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository }}/my-image-name:latest


