name: EAI-DEEPSTREAM

on:
  push:
    branches: [ "dev" ]
    paths: 
      - "eai_deepstream/**"
  
  pull_request:
    branches: [ "dev" ]
    paths: 
      - "eai_deepstream/**"

permissions:
  contents: read
  packages: write

jobs:
  
  docker-publish-deepstream:
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: eai_deepstream

    steps:
    - uses: actions/checkout@v3
      
    - name: Build the Docker image
      run: |
        repo_name=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        docker build . --file docker/deepstream.Dockerfile --tag ghcr.io/$repo_name/eai_deepstream:v1.0.0

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push Docker image
      run: |
        repo_name=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        docker push ghcr.io/$repo_name/eai_deepstream:v1.0.0


